package dao.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-11-28T23:06:22.991-03:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "LogisticaMonitoreoBeanService", 
                  wsdlLocation = "http://5.7.56.6:8080/LogisticaMonitoreo/LogisticaMonitoreoWS?wsdl",
                  targetNamespace = "http://webservice/") 
public class LogisticaMonitoreoBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice/", "LogisticaMonitoreoBeanService");
    public final static QName LogisticaMonitoreoWSPort = new QName("http://webservice/", "LogisticaMonitoreoWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://5.7.56.6:8080/LogisticaMonitoreo/LogisticaMonitoreoWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LogisticaMonitoreoBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://5.7.56.6:8080/LogisticaMonitoreo/LogisticaMonitoreoWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LogisticaMonitoreoBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LogisticaMonitoreoBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogisticaMonitoreoBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
   

    /**
     *
     * @return
     *     returns LogisticaMonitoreoWS
     */
    @WebEndpoint(name = "LogisticaMonitoreoWSPort")
    public LogisticaMonitoreoWS getLogisticaMonitoreoWSPort() {
        return super.getPort(LogisticaMonitoreoWSPort, LogisticaMonitoreoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogisticaMonitoreoWS
     */
    @WebEndpoint(name = "LogisticaMonitoreoWSPort")
    public LogisticaMonitoreoWS getLogisticaMonitoreoWSPort(WebServiceFeature... features) {
        return super.getPort(LogisticaMonitoreoWSPort, LogisticaMonitoreoWS.class, features);
    }

}
